### ISSUE TITLE
Can't disable elcord-mode

### ISSUE THREAD

**Issue by ShadowMitia** [Mstrodl/elcord#4]
I can't seem to be able to disable `elcord`, I tried calling `elcord-mode` but it still sends updadtes to the Rich Presence, however long I wait. Calling it several times does not seem to help either.

Extract from my `*messages*`:

> Starting Emacs daemon.
> When done with this frame, type C-x 5 0
> Configuring package helm...done (0.237s)
> Elcord mode enabled
> elcord: attempting reconnect..
> elcord: connecting...
> elcord: connected. starting updates
> Elcord mode disabled
> elcord: disconnected
> elcord: attempting reconnect..
> elcord: connecting...
> elcord: connected. starting updates
> Elcord mode enabled
> elcord: attempting reconnect..
> elcord: connecting...
> Elcord mode disabled
> elcord: disconnected
> elcord: attempting reconnect..
> elcord: connecting...
> elcord: connected. starting updates

I'm using Fedora 27 and Emacs 25.3.1

**Comment by Mstrodl** [comment]
@ShadowMitia Hm, looks like we forgot to disable the reconnection code once the mode is disabled

**Comment by Mstrodl** [comment]
@ShadowMitia This should be fixed in the latest commit ([0cef4ca](https://github.com/Mstrodl/elcord/commit/0cef4ca13b00d79507292d5591be8ffb7df5a9ca))!

**Comment by ShadowMitia** [comment]
It disconnects fine now, thanks!

But once disconnected it still shows the last update in the Rich Presence in Discord. And it doesn't seem to be going away even after waiting for a while... On the plus side it doesn't update when changing buffers at all!

The only way to make the Rich Presence go back to normal right now is by either quitting emacs or stopping the daemon if running with it.

**Comment by Mstrodl** [comment]
Hm, something tells me that might be more on Discord's end than anything... See if you can take a screenshot of the console in the inspector (`ctrl-shift-i`) and mark off with arrows or something when you did certain things... :/

**Comment by Mstrodl** [comment]
Hm, it looks like it might just be Discord tracking the PID we send in the SET_ACTIVITY packet.... I don't think we can actually do anything about that

**Comment by ShadowMitia** [comment]
Yeah, sounds like Discord Rich Presence was not designed for this...

But if it tracks the PID I understand it not working when in daemon mode, but it does the same when emacs is run in standalone. Shouldn't it detect emacs not running anymore then? Maybe I did something, I should probably double check....

**Comment by Mstrodl** [comment]
@ShadowMitia Huh? I'm not sure you understand what I'm saying... I'm trying to say that the mode being disabled currently acts funny because Discord doesn't stop recognizing emacs as being played until the pid we send it is killed, even if we completely disconnect it from Discord's RPC server

**Comment by ShadowMitia** [comment]
Right, yeah my bad.... Silly remark...

You said to use a dummy process for its PID earlier, but couldn't you have elcord run in that process directly instead? Then you wouldn't have a dummy process^^

**Comment by Mstrodl** [comment]
@ShadowMitia Yeah, but that'd require us to either call a headless emacs and somehow get our information back and forth which imo seems like a kludgy solution... My thought was running something like `cat` and then we'd be able to kill it at will. Again, just a thought

**Comment by ShadowMitia** [comment]
Keeping in mind that I'm very new at elisp, and bad at processes, but couldn't having an [asynchronous process](https://www.gnu.org/software/emacs/manual/html_node/elisp/Asynchronous-Processes.html) solve everything? 
You would still have the mode active on the main emacs thread, just have the part hooked up to the RPC in a subprocess. But I'm guessing it shares the same PID.

In any case, I think I've made this issue diverge sufficiently from its original purpose^^ You should probably close this. I'm sure a solution will turn up someday^^

**Comment by Mstrodl** [comment]
@ShadowMitia I finally figured out how to do this! After checking the source, we can actually send `null` as the activity and it will simply clear itself!

**Comment by ShadowMitia** [comment]
@Mstrodl Congrats! Thanks for working on this issue! I hope it didn't give you any sleepless nights :grin:

**Comment by Mstrodl** [comment]
@ShadowMitia No worries, it's more that I stumbled upon it :P
