### ISSUE TITLE
`Error running 'elcord--start-idle'` message displayed even when elcord-quiet is set to true

### ISSUE THREAD

**Issue by OpenSauce04** [Mstrodl/elcord#98]
I have elcord in my .emacs and it is always loaded when Emacs is opened. I also have `elcord-quiet` set to true to suppress any messages related to connecting to Discord as I do not always (or even often) have Discord open when using Emacs

Despite attempting to suppress all messages related to elcord using the above configuration, I still recieve the following error intermittedly when I idle in Emacs for too long, presumably due to a failure to connect to Discord:
```
Error running timer ‘elcord--start-idle’: (wrong-type-argument timerp nil)
```

Assuming that the appearance of this message at all isn't itself a bug, I believe that `elcord-quiet` should suppress this message.

**Comment by Mstrodl** [comment]
Not seeing this behavior on my machine. I did note a different issue though, fixed in 97f57d6

**Comment by Mstrodl** [comment]
Some information about my system, where I am not seeing the issue:
```
$ emacs --version
GNU Emacs 29.4
Copyright (C) 2024 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
$
```
Running elcord from `master` on git.
Could you share your operating system version, emacs version, and elcord version?

**Comment by OpenSauce04** [comment]
I am still experiencing this on the latest Melpa version as of today
I am running Emacs 30.0.93 with elcord 20250113.131 on Gentoo Linux

**Comment by poniponiponiponiponiponiponiponiponi** [comment]
I'm seeing the same error with elcord 20250304.1743 on ArchLinux

```
[poni@Shinji ~] λδ emacs --version
GNU Emacs 30.1
Copyright (C) 2025 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
[poni@Shinji ~] λδ uname -a
Linux Shinji 6.14.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 20 Apr 2025 12:38:52 +0000 x86_64 GNU/Linux
```
